# Generated by Django 4.1.2 on 2022-11-13 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("github", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("mobile", models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("github", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("mobile", models.PositiveIntegerField(blank=True)),
                ("varsity_name", models.CharField(max_length=255)),
                ("degree", models.CharField(max_length=50)),
                ("stream", models.CharField(max_length=100)),
                ("passing_year", models.DateField()),
                ("result", models.CharField(max_length=5)),
                ("school10_name", models.CharField(max_length=255)),
                ("board10", models.CharField(max_length=100)),
                ("passing_year10", models.DateField()),
                ("result10", models.CharField(max_length=5)),
                ("school12_name", models.CharField(max_length=255)),
                ("board12", models.CharField(max_length=100)),
                ("passing_year12", models.DateField()),
                ("result12", models.CharField(max_length=5)),
                ("skill_detail", models.TextField()),
                ("project_detail", models.TextField(blank=True)),
                ("achievement_detail", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_detail", models.TextField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumeGenerator.personalinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_detail", models.TextField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumeGenerator.personalinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("varsity_name", models.CharField(max_length=255)),
                ("degree", models.CharField(max_length=50)),
                ("stream", models.CharField(max_length=100)),
                ("passing_year", models.DateField()),
                ("result", models.CharField(max_length=5)),
                ("school10_name", models.CharField(max_length=255)),
                ("board10", models.CharField(max_length=100)),
                ("passing_year10", models.DateField()),
                ("result10", models.CharField(max_length=5)),
                ("school12_name", models.CharField(max_length=255)),
                ("board12", models.CharField(max_length=100)),
                ("passing_year12", models.DateField()),
                ("result12", models.CharField(max_length=5)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumeGenerator.personalinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Achievements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("achievement_detail", models.TextField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumeGenerator.personalinfo",
                    ),
                ),
            ],
        ),
    ]
