# Generated by Django 4.1 on 2022-11-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeGenerator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='person',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='about_detail',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='place',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='title',
        ),
        migrations.AddField(
            model_name='resume',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
