# Generated by Django 4.1.2 on 2022-11-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "resumeGenerator",
            "0002_remove_experience_person_remove_resume_about_detail_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="resume", name="award_detail",),
        migrations.DeleteModel(name="Awards",),
    ]
