# Generated by Django 4.1.2 on 2022-11-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resumeGenerator", "0003_remove_resume_award_detail_delete_awards"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="award_detail",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="Awards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("award_detail", models.TextField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumeGenerator.personalinfo",
                    ),
                ),
            ],
        ),
    ]
