# Generated by Django 4.1.2 on 2022-11-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumeGenerator", "0004_resume_award_detail_awards"),
    ]

    operations = [
        migrations.RemoveField(model_name="resume", name="award_detail",),
        migrations.DeleteModel(name="Awards",),
    ]
