# Generated by Django 4.1.2 on 2022-11-12 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("resumeGenerator", "0005_remove_resume_award_detail_delete_awards"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="board10",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="board12",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="passing_year10",
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="passing_year12",
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="result10",
            field=models.CharField(default="", max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="result12",
            field=models.CharField(default="", max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="school10_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="school12_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="varsity_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="achievement_detail",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="board10",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="board12",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="passing_year10",
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="passing_year12",
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="result10",
            field=models.CharField(default="", max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="result12",
            field=models.CharField(default="", max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="school10_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="school12_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resume",
            name="stream",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resume", name="degree", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="resume", name="result", field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="resume",
            name="varsity_name",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="Achievements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("achievement_detail", models.TextField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumeGenerator.personalinfo",
                    ),
                ),
            ],
        ),
    ]
